### ISSUE TITLE
Rename a, b, c to step1, step2, step3, ...

### ISSUE THREAD

**Issue by alarbada** [praveen-kumar-rr/rescript-async#1]
Thanks for the idea! I find a bit confusing the a b c criteria, maybe renaming all to using step1, step2, ... ? That could make it much clearer.

**Comment by praveen-kumar-rr** [comment]
@not-rusty The label actually corresponds to the `key` in the object that is passed into the next function in the sequence. 
I personally feel, `{"a": 'a}` would be better than `{"step1": 'a}`. It follows natural variable naming.

**Comment by alarbada** [comment]
To each their own :)
